version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "10010:6379"
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "10020:3306"
    environment:
      MYSQL_ROOT_PASSWORD: choongang
    networks:
      - my-network