networks:
  my-network:
    driver: bridge

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "10120:9411"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "10110:9090"
    networks:
      - my-network

#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "10100:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=lsek
#      - GF_SECURITY_ADMIN_PASSWORD=grafanatest
#    networks:
#      - my-network
#    depends_on:
#      - prometheus
#      - zipkin
